name: Load React Native Harness configuration
inputs:
  runner:
    description: The runner to use
    required: true
    type: string
  projectRoot:
    description: The project root directory
    required: false
    type: string
outputs:
  config:
    description: The entire React Native Harness configuration as JSON
runs:
  using: 'node20'
  main: './index.cjs'
